### ISSUE TITLE
Clear IVCApps following installation

### ISSUE THREAD

**Issue by danijeljw** [oseyx/SOE_Staging#39]
Remove all the data in the IVC Apps folder after the machine has been finalised

-----------
#### Tasks:
- [x] Move the `AppAssocations.xml` to the root of C:\IVCApps b86ea8e
- [ ] Delete the `SOE_Config.ps1` file
- [ ] Add Verbose steps to `POST-SOE-DEPLOYMENT.ps1`

**Comment by danijeljw** [comment]
The IVCApps folder is now going to be marked as Hidden. Add this to the documentation only.

Marked in issue #51 for more details
